import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LinkComponent from "./_component/ui-elements/LinkComponent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-400">
          <ul className="text-2xl p-4 flex justify-evenly">
            <LinkComponent url="/" text="Home"></LinkComponent>
            <LinkComponent url="/currentweather" text="Current"></LinkComponent>
            <LinkComponent
              url="/forecastweather"
              text="Forecast"
            ></LinkComponent>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
